options(java.parameters = "-Xmx8g")

library(shiny)
# library(dygraphs)
library(leaflet)
library(lubridate)
library(openair)
library(magrittr)
library(dplyr)
library(markdown)
# library(shinyBS)
library(DT)
library(RJDBC)
library(DBI)
library(tidyr)
library(tibble)
library(dplyr)
library(readr)
library(xlsx)
# library(htmlwidgets) 
# library(webshot)
# library(knitr)
library(readxl)

source("rangofecha.R")
source("corrector_hora_actual.R")
#source("cargadatos.R")
titulo <- read_excel("www/tabla_maestra.xlsx", sheet = "titulo")
bd.1h <- readRDS(file = "bd.1h.rds")
corte <- ymd_hms("2021-09-22 23:55:00")
 cota <- ymd("2021-09-23")
